# Generated by Django 4.1.3 on 2023-09-03 19:34

import advertisement_app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('edit_at', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования')),
                ('pub_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
                ('published', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('editor', models.CharField(blank=True, max_length=255, verbose_name='Отредактировал')),
                ('autor', models.CharField(default='Правление СНТ', max_length=255, verbose_name='Автор')),
                ('tag_news', models.CharField(blank=True, choices=[('notification', 'Уведомление'), ('important', 'Важно')], default='', max_length=12, verbose_name='Пометка')),
                ('title_news', models.CharField(max_length=255, verbose_name='Заголовок объявления')),
                ('content_news', models.TextField()),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
                'ordering': ['pub_date'],
            },
        ),
        migrations.CreateModel(
            name='FileNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, verbose_name='Название файла')),
                ('file_descr', models.CharField(blank=True, max_length=255, verbose_name='Описание файла')),
                ('file', models.FileField(upload_to=advertisement_app.models.get_file_storage_path)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_news', to='advertisement_app.advertisement')),
            ],
        ),
    ]
