# Generated by Django 4.1.3 on 2023-09-04 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='edit_at',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='published',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='state_news',
            field=models.CharField(default='hidden', max_length=6, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='tag_news',
            field=models.CharField(choices=[('notification', 'Уведомление'), ('important', 'Важно'), ('message', 'Сообщение')], default='message', max_length=12, verbose_name='Пометка'),
        ),
    ]
