# Generated by Django 4.1.3 on 2023-09-04 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement_app', '0002_remove_advertisement_edit_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='state_news',
            field=models.CharField(choices=[('public', 'Опубликовано'), ('hidden', 'Скрыто')], default='hidden', max_length=6, verbose_name='Опубликовано'),
        ),
    ]
