# Generated by Django 4.1.3 on 2024-03-05 06:06

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Значение ответа')),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Суть вопроса')),
                ('description', models.TextField(blank=True, help_text='Не обязательно', verbose_name='Дополнительные пояснения')),
                ('answers', models.ManyToManyField(to='voting_app.answer', verbose_name='Варианты ответов')),
            ],
            options={
                'verbose_name': 'Вопрос для голосования',
                'verbose_name_plural': 'Вопросы для голосования',
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='MeetingProtocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.SmallIntegerField(verbose_name='Номер документа')),
                ('title', models.CharField(default='Протокол голосования с применением технических средств', max_length=255, verbose_name='Название документа')),
                ('start_event', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата проведения')),
                ('close_event', models.DateTimeField(default=datetime.datetime(2024, 3, 12, 6, 6, 3, 994874, tzinfo=datetime.timezone.utc), verbose_name='Дата закрытия')),
                ('agenda', models.TextField(blank=True, help_text='Не обязательно', null=True, verbose_name='Повестка')),
                ('status', models.CharField(choices=[('open', 'Открыт'), ('close', 'Закрыт')], default='open', max_length=5, verbose_name='Состояние')),
            ],
            options={
                'verbose_name': 'Протокол голосования',
                'verbose_name_plural': 'Протоколы голосования',
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время голоса')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL, verbose_name='Участник')),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='voting_app.meetingprotocol', verbose_name='Протокол')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='voting_app.issue', verbose_name='Вопрос')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='voting_app.answer', verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Голос',
                'verbose_name_plural': 'Голоса',
            },
        ),
        migrations.AddField(
            model_name='issue',
            name='protocol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='voting_app.meetingprotocol', verbose_name='Протокол'),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('protocol', 'question', 'owner'), name='unique_vote'),
        ),
    ]
