# Generated by Django 4.1.3 on 2024-03-05 18:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingprotocol',
            name='close_event',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 12, 18, 22, 36, 220654, tzinfo=datetime.timezone.utc), verbose_name='Дата закрытия'),
        ),
    ]
