# Generated by Django 4.1.3 on 2023-09-02 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_url', models.URLField(blank=True, max_length=255, verbose_name='Адрес сайта')),
                ('site_title', models.CharField(blank=True, max_length=255, verbose_name='Заголовок сайта')),
                ('site_email', models.EmailField(blank=True, max_length=255, verbose_name='Официальная почта')),
                ('site_social', models.URLField(blank=True, max_length=255, verbose_name='Адрес VK')),
                ('site_telegram', models.URLField(blank=True, max_length=255, verbose_name='Адрес ТГ')),
                ('site_postal', models.CharField(blank=True, max_length=255, verbose_name='Почтовый адрес')),
            ],
            options={
                'verbose_name': 'Конфигурация',
                'verbose_name_plural': 'Конфигурации',
            },
        ),
    ]
