# Generated by Django 4.1.3 on 2023-10-05 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.FileField(upload_to='category/', verbose_name='Выбор файла')),
                ('alt', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_url', models.URLField(blank=True, max_length=255, verbose_name='Адрес сайта')),
                ('site_title', models.CharField(blank=True, max_length=255, verbose_name='Заголовок сайта')),
                ('site_email', models.EmailField(blank=True, max_length=255, verbose_name='Официальная почта')),
                ('site_social', models.URLField(blank=True, max_length=255, verbose_name='Адрес VK')),
                ('site_telegram', models.URLField(blank=True, max_length=255, verbose_name='Адрес ТГ')),
                ('site_postal', models.CharField(blank=True, max_length=255, verbose_name='Почтовый адрес')),
                ('site_inn', models.CharField(blank=True, max_length=10, verbose_name='ИНН')),
                ('site_kpp', models.CharField(blank=True, max_length=9, verbose_name='КПП')),
                ('site_bank', models.CharField(blank=True, max_length=255, verbose_name='Юр. адрес банка')),
                ('correspondent_account', models.CharField(blank=True, max_length=20, verbose_name='Кор. счет')),
                ('site_bik', models.CharField(blank=True, max_length=9, verbose_name='БИК')),
                ('payment_account', models.CharField(blank=True, max_length=20, verbose_name='Расчетный. счет')),
            ],
            options={
                'verbose_name': 'Конфигурация',
                'verbose_name_plural': 'Конфигурации',
            },
        ),
        migrations.CreateModel(
            name='DocumentMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='URL пункта меню')),
                ('order', models.CharField(blank=True, max_length=10, null=True, verbose_name='Порядок пунктов')),
                ('level', models.IntegerField(blank=True, null=True, verbose_name='Уровень вложенности')),
                ('position', models.IntegerField(blank=True, default=99, null=True, verbose_name='Позиция')),
                ('is_public', models.BooleanField(default=True, verbose_name='Публично')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_menu', to='site_settings.documentimage')),
                ('parent', models.ForeignKey(blank=True, limit_choices_to={'level__lt': 3}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submenu', to='site_settings.documentmenu', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Пункт',
                'verbose_name_plural': 'Пункты меню',
                'ordering': ['order'],
            },
        ),
    ]
