# Generated by Django 4.1.3 on 2024-03-16 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentmenu',
            name='parent',
            field=models.ForeignKey(blank=True, limit_choices_to={'level__lt': 10}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submenu', to='site_settings.documentmenu', verbose_name='Родительская категория'),
        ),
    ]
