# Generated by Django 4.1.3 on 2023-09-17 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='correspondent_account',
            field=models.CharField(blank=True, max_length=20, verbose_name='Кор. счет'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='payment_account',
            field=models.CharField(blank=True, max_length=20, verbose_name='Расчетный. счет'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_bank',
            field=models.CharField(blank=True, max_length=255, verbose_name='Юр. адрес банка'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_bik',
            field=models.CharField(blank=True, max_length=9, verbose_name='БИК'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_inn',
            field=models.CharField(blank=True, max_length=10, verbose_name='ИНН'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_kpp',
            field=models.CharField(blank=True, max_length=9, verbose_name='КПП'),
        ),
    ]
