# Generated by Django 4.1.3 on 2023-09-19 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_sitesettings_correspondent_account_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.FileField(upload_to='category/', verbose_name='Выбор файла')),
                ('alt', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(max_length=30, unique=True, verbose_name='URL пункта меню')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_menu', to='site_settings.documentimage')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submenu', to='site_settings.documentmenu', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Пункт',
                'verbose_name_plural': 'Пункты меню',
            },
        ),
    ]
