# Generated by Django 4.1.3 on 2023-09-19 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0003_documentimage_documentmenu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentmenu',
            options={'ordering': ['title'], 'verbose_name': 'Пункт', 'verbose_name_plural': 'Пункты меню'},
        ),
        migrations.AlterField(
            model_name='documentmenu',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='URL пункта меню'),
        ),
    ]
