# Generated by Django 4.1.3 on 2023-09-20 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0004_alter_documentmenu_options_alter_documentmenu_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentmenu',
            options={'ordering': ['position', 'left'], 'verbose_name': 'Пункт', 'verbose_name_plural': 'Пункты меню'},
        ),
        migrations.AddField(
            model_name='documentmenu',
            name='left',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentmenu',
            name='level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentmenu',
            name='position',
            field=models.IntegerField(blank=True, null=True, verbose_name='Позиция'),
        ),
        migrations.AddField(
            model_name='documentmenu',
            name='published',
            field=models.BooleanField(default=True, verbose_name='Опубликован'),
        ),
        migrations.AddField(
            model_name='documentmenu',
            name='right',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
