# Generated by Django 4.1.3 on 2023-09-21 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0006_alter_documentmenu_options_remove_documentmenu_left_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentmenu',
            name='order',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Порядок пунктов'),
        ),
    ]
