# Generated by Django 4.1.3 on 2023-10-05 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0008_alter_documentmenu_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentmenu',
            name='order_parent',
        ),
    ]
