# Generated by Django 4.1.3 on 2024-03-12 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('edit_at', models.DateTimeField(auto_now=True, verbose_name='Отредактирован')),
                ('active', models.BooleanField(default=True, help_text='Открыт или закрыт', verbose_name='Статус')),
                ('hidden', models.BooleanField(default=False, help_text='Скрытие модератором', verbose_name='Скрыт')),
                ('author', models.CharField(max_length=255, verbose_name='Автор')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Аккаунт')),
            ],
            options={
                'verbose_name': 'Тема обсуждения',
                'verbose_name_plural': 'Темы обсуждения',
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('edit_at', models.DateTimeField(auto_now=True, verbose_name='Отредактирован')),
                ('hidden', models.BooleanField(default=False, help_text='Скрытие модератором', verbose_name='Скрыт')),
                ('author', models.CharField(max_length=255, verbose_name='Автор')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recomments', to='forum_app.comment', verbose_name='Ответ на коммент')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='forum_app.post', verbose_name='Топикстартер')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Аккаунт')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ('post', 'pk'),
            },
        ),
    ]
