# Generated by Django 4.1.3 on 2023-10-05 23:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now=True, verbose_name='Создано')),
                ('update_at', models.DateTimeField(auto_now_add=True, verbose_name='Изменено')),
                ('title', models.CharField(max_length=255, verbose_name='Название документа')),
                ('content', models.TextField(blank=True, help_text='Может быть заполнено автоматически при загрузке документов в формате docx или xlsx', verbose_name='Содержание документа (в html)')),
                ('doc_files', models.FileField(blank=True, upload_to='doc/%Y/%B/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['docx', 'jpg', 'xlsx'], message='Файл не поддерживается. Разрешенные расширения .jpg .docx .xlsx')], verbose_name='Файл в формате .docx, .xlsx или .jpg')),
                ('is_public', models.BooleanField(default=False, verbose_name='Публично')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='site_settings.documentmenu', verbose_name='Пункт меню')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы и отчетность',
            },
        ),
    ]
