# Generated by Django 4.1.3 on 2023-10-05 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('site_settings', '0008_alter_documentmenu_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now=True, verbose_name='Создано')),
                ('update_at', models.DateTimeField(auto_now_add=True, verbose_name='Изменено')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('resource', models.TextField(blank=True, verbose_name='HTML текст')),
                ('doc_files', models.FileField(blank=True, upload_to='doc/%Y/%B/')),
                ('is_public', models.BooleanField(default=False, verbose_name='Публично')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='site_settings.documentmenu', verbose_name='Пункт меню')),
            ],
        ),
    ]
