# Generated by Django 4.1.3 on 2023-08-30 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('government_app', '0002_alter_news_editor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateTimeField(blank=True, verbose_name='Опубликовано'),
        ),
    ]
