# Generated by Django 4.1.3 on 2023-08-30 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('government_app', '0005_alter_news_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='tag_news',
            field=models.CharField(blank=True, choices=[('notification', 'Уведомление'), ('important', 'Важно')], default='', max_length=12, verbose_name='Пометка'),
        ),
    ]
